import { useEffect, useMemo, useRef, useState } from 'react';
import { useVirtualizer } from '@tanstack/react-virtual';
import { ArrowDown, ArrowUp, Check, Clock3, Disc3, Heart, LibraryBig, ListMusic, Pencil, Play, Plus, RefreshCw, Search, Trash2, Users, X } from 'lucide-react';
import type { Collections, Library, Playlist, Track } from './types';
import { time } from './types';
import type { Sort } from './libraryModel';
import { localSearchSource, localTracksForHits, sortLabels, sortTracks } from './libraryModel';
import { recentlyAddedTracks, type NavigationPage } from './navigationModel';
import type { PlayerModel } from './player';
import TrackList from './TrackList';
import TrackContextMenu from './TrackContextMenu';
import CollectionContextMenu, { type CollectionMenuTarget } from './CollectionContextMenu';
import { enqueueGroup, openContextMenu, playlistAddAction } from './trackContextMenuModel';
import { Cover } from './ui';
import SoulseekSearchView from './SoulseekSearchView';
import type { SoulseekResult } from './soulseekSearch';

export type Mutation=(action:Record<string,unknown>)=>Promise<Collections|undefined>;
type ContentPage=Exclude<NavigationPage,{kind:'visualizer'}>;
type Props={page:ContentPage;query:string;onQueryChange:(query:string)=>void;library:Library;collections:Collections;mutate:Mutation;busy:boolean;player:PlayerModel;navigate:(page:NavigationPage)=>void;onScan:()=>void;scanning:boolean;notice:(text:string)=>void;trashAvailable:boolean;onMoveToTrash:(track:Track)=>void;onRemoveFromLibrary:(track:Track)=>void;onViewMetadata:(track:Track)=>void;soulseek:{enabled:boolean;configured:boolean;request:{id:number;query:string}|null;onSearch:()=>void;onDownload:(result:SoulseekResult)=>void;downloadState:(result:SoulseekResult)=>'pending'|'added'|null}};
type Card={id:number;title:string;subtitle:string;track:Track|null;menuTarget:CollectionMenuTarget};
function EntityGrid({items,artists=false,onOpen,onContextMenu,dropTargets=false}:{items:Card[];artists?:boolean;onOpen:(id:number)=>void;onContextMenu:(target:CollectionMenuTarget,point:{x:number;y:number})=>void;dropTargets?:boolean}) {
  const ref=useRef<HTMLDivElement>(null),[columns,setColumns]=useState(4);
  useEffect(()=>{const el=ref.current;if(!el)return;const observer=new ResizeObserver(()=>setColumns(Math.max(2,Math.floor(el.clientWidth/185))));observer.observe(el);return()=>observer.disconnect();},[]);
  const rows=useVirtualizer({count:Math.ceil(items.length/columns),getScrollElement:()=>ref.current,estimateSize:()=>248,overscan:2});
  return <div className="entity-scroll" ref={ref}><div style={{height:rows.getTotalSize(),position:'relative'}}>{rows.getVirtualItems().map(row=><div key={row.key} className="entity-grid-row" style={{position:'absolute',top:0,width:'100%',height:248,transform:`translateY(${row.start}px)`,gridTemplateColumns:`repeat(${columns},minmax(0,1fr))`}}>{items.slice(row.index*columns,(row.index+1)*columns).map(item=><button key={item.id} className={`entity-card ${artists?'artist-card':''}`} onClick={()=>onOpen(item.id)} onContextMenu={event=>openContextMenu(event,point=>onContextMenu(item.menuTarget,point))} data-playlist-id={dropTargets?item.id:undefined}><Cover track={item.track}/><strong>{item.title}</strong><small>{item.subtitle}</small></button>)}</div>)}</div>{!items.length&&<div className="empty-inline">Нет элементов.</div>}</div>;
}
export function PlaylistEditor({playlist,onClose,mutate,onSaved,busy}:{playlist?:Playlist;onClose:()=>void;mutate:Mutation;onSaved:(id:number)=>void;busy:boolean}) {
  const ref=useRef<HTMLDialogElement>(null),[name,setName]=useState(playlist?.name||''),[description,setDescription]=useState(playlist?.description||'');
  useEffect(()=>{ref.current?.showModal();},[]);
  return <dialog ref={ref} className="folder-dialog" onCancel={onClose}><form className="dialog-body playlist-form" onSubmit={async e=>{e.preventDefault();const result=await mutate(playlist?{type:'edit_playlist',id:playlist.id,name,description}:{type:'create_playlist',name,description});if(result){onSaved(playlist?.id??result.playlists[0].id);onClose();}}}><div className="section-heading"><h2>{playlist?'Изменить плейлист':'Новый плейлист'}</h2><button type="button" className="icon-button" aria-label="Закрыть редактор" onClick={onClose}><X size={20}/></button></div><label htmlFor="playlist-name">Название</label><input autoFocus id="playlist-name" placeholder="Например, Ночная дорога" value={name} maxLength={120} required onChange={e=>setName(e.target.value)}/><label htmlFor="playlist-description">Описание</label><textarea id="playlist-description" value={description} maxLength={2000} rows={3} placeholder="Несколько слов о подборке" onChange={e=>setDescription(e.target.value)}/><button className="primary-button" disabled={busy||!name.trim()} type="submit"><Check size={16}/>{playlist?'Сохранить':'Создать'}</button></form></dialog>;
}
function ActionDialog({track,onClose,children}:{track:Track;onClose:()=>void;children:React.ReactNode}) {
  const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();},[]);
  return <dialog ref={ref} className="folder-dialog track-dialog" onCancel={onClose}><div className="dialog-body"><div className="section-heading"><div className="dialog-track"><Cover track={track} size="small"/><div><h3>{track.title}</h3><small>{track.artist}</small></div></div><button className="icon-button" aria-label="Закрыть действия" onClick={onClose}><X size={18}/></button></div>{children}</div></dialog>;
}

export default function CollectionView({page,query,onQueryChange,library,collections,mutate,busy,player,navigate,onScan,scanning,notice,trashAvailable,onMoveToTrash,onRemoveFromLibrary,onViewMetadata,soulseek}:Props) {
  const [sort,setSort]=useState<Sort>('default'),[descending,setDescending]=useState(false),[editor,setEditor]=useState<Playlist|true|null>(null),[actions,setActions]=useState<{track:Track;index:number}|null>(null),[contextMenu,setContextMenu]=useState<{track:Track;point:{x:number;y:number}}|null>(null),[collectionMenu,setCollectionMenu]=useState<{target:CollectionMenuTarget;point:{x:number;y:number}}|null>(null),[destination,setDestination]=useState(''),[deleteOpen,setDeleteOpen]=useState<Playlist|null>(null);
  const pageKey=page.kind+('id' in page?page.id:'');
  useEffect(()=>{setSort('default');setDescending(false);setActions(null);setContextMenu(null);setCollectionMenu(null);setDeleteOpen(null);},[pageKey]);
  const byId=useMemo(()=>new Map(library.tracks.map(t=>[t.id,t])),[library.tracks]);
  const likes=useMemo(()=>new Set(collections.likes),[collections.likes]);
  const source=useMemo(()=>localSearchSource(library.tracks),[library.tracks]);
  const searchHits=useMemo(()=>page.kind==='search'?source.searchNow(query):[],[page.kind,query,source]);
  const searchTracks=useMemo(()=>page.kind==='search'?localTracksForHits(library.tracks,searchHits):[],[library.tracks,searchHits,page.kind]);
  const albums=useMemo(()=>{const groups=new Map<number,Track[]>();for(const t of library.tracks){if(!groups.has(t.album_id))groups.set(t.album_id,[]);groups.get(t.album_id)!.push(t);}return groups;},[library.tracks]);
  const artists=useMemo(()=>{const groups=new Map<number,Track[]>();for(const t of library.tracks){if(!groups.has(t.artist_id))groups.set(t.artist_id,[]);groups.get(t.artist_id)!.push(t);}return groups;},[library.tracks]);
  const playlist=page.kind==='playlist'?collections.playlists.find(p=>p.id===page.id):undefined;
  const raw=page.kind==='artist'?(artists.get(page.id)||[]):page.kind==='album'?(albums.get(page.id)||[]):page.kind==='playlist'?(playlist?.entries.map(e=>byId.get(e.track_id)).filter((t):t is Track=>!!t)||[]):page.kind==='liked'?collections.likes.map(id=>byId.get(id)).filter((t):t is Track=>!!t):page.kind==='history'?collections.history.map(e=>byId.get(e.track_id)).filter((t):t is Track=>!!t):page.kind==='recentlyAdded'?recentlyAddedTracks(library.tracks):page.kind==='search'?searchTracks:page.kind==='queue'?player.queue.items.slice(player.queue.cursor+1).map(e=>e.track):library.tracks;
  const fixedOrder=['playlist','history','queue','recentlyAdded'].includes(page.kind);
  const tracks=useMemo(()=>sortTracks(raw,fixedOrder?'default':sort,fixedOrder?false:descending),[raw,sort,descending,fixedOrder]);
  const searchEmpty=page.kind==='search'&&!tracks.length;
  const title=page.kind==='artist'?(raw[0]?.artist||'Исполнитель'):page.kind==='album'?(raw[0]?.album||'Альбом'):page.kind==='playlist'?(playlist?.name||'Плейлист не найден'):{home:'Главная',library:'Медиатека',recentlyAdded:'Недавно добавлено',artists:'Исполнители',albums:'Альбомы',liked:'Любимые треки',playlists:'Плейлисты',history:'Недавно слушали',queue:'Очередь',search:'Поиск',downloads:'Загрузки',lyrics:'Тексты песен',lyricsView:'Текст песни'}[page.kind];
  const icon=page.kind==='liked'?<Heart size={46}/>:page.kind==='artists'||page.kind==='artist'?<Users size={46}/>:page.kind==='albums'||page.kind==='album'?<Disc3 size={46}/>:page.kind==='history'||page.kind==='recentlyAdded'?<Clock3 size={46}/>:page.kind==='queue'||page.kind==='playlists'||page.kind==='playlist'?<ListMusic size={46}/>:<LibraryBig size={46}/>;
  const cards:Card[]=page.kind==='artists'?[...artists].map(([id,ts])=>({id,title:ts[0].artist,subtitle:`${ts.length} треков · ${new Set(ts.map(t=>t.album_id)).size} альбомов`,track:ts.find(t=>t.cover)||ts[0],menuTarget:{kind:'artist',id,title:ts[0].artist,tracks:ts}})):page.kind==='albums'?[...albums].map(([id,ts])=>({id,title:ts[0].album,subtitle:`${ts[0].album_artist}${ts[0].year?` · ${ts[0].year}`:''}`,track:ts.find(t=>t.cover)||ts[0],menuTarget:{kind:'album',id,title:ts[0].album,tracks:ts}})):collections.playlists.map(p=>{const playlistTracks=p.entries.map(entry=>byId.get(entry.track_id)).filter((track):track is Track=>!!track);return {id:p.id,title:p.name,subtitle:`${p.entries.length} треков`,track:playlistTracks[0]||null,menuTarget:{kind:'playlist',id:p.id,title:p.name,tracks:playlistTracks,playlist:p}};});
  const grid=['artists','albums','playlists'].includes(page.kind);
  const sortedCards=sort==='default'?(descending?[...cards].reverse():cards):[...cards].sort((a,b)=>(descending?-1:1)*a.title.localeCompare(b.title,'ru',{numeric:true}));
  function showActions(track:Track,index:number){setDestination(String(collections.playlists[0]?.id||''));setActions({track,index});}
  async function mutateClose(action:Record<string,unknown>){if(await mutate(action))setActions(null);}
  const interactions={likes,onLike:(t:Track)=>void mutate({type:'like',track_id:t.id,liked:!likes.has(t.id)}),onActions:showActions,onContextMenu:(track:Track,point:{x:number;y:number})=>setContextMenu({track,point}),onArtist:(id:number)=>navigate({kind:'artist',id}),onAlbum:(id:number)=>navigate({kind:'album',id}),busy:busy||player.busy};
  const toolbarLabel=page.kind==='search'?(query?`Поиск: «${query}»`:'Введите запрос'):page.kind==='playlist'?'Перетащите сюда треки или добавьте через меню ⋯':page.kind==='queue'?'Далее по списку':page.kind==='history'?'Последние 200 запусков':page.kind==='recentlyAdded'?'Сначала новые':'';
  const trackList=<TrackList tracks={tracks} currentId={page.kind==='queue'?null:player.status.id} playing={player.status.playing} onPlay={(t,i)=>page.kind==='queue'?void player.jump(player.queue.cursor+1+i):void player.play(t,tracks,i,playlist?{kind:'playlist',playlistId:playlist.id}:undefined)} {...interactions} emptyText={page.kind==='queue'?'Очередь пуста. Добавьте трек через контекстное меню или выберите «Слушать следующим».':page.kind==='search'?(query.trim()?'Ничего не найдено в локальной библиотеке. Попробуйте изменить запрос.':'Введите запрос для поиска по локальной библиотеке.'):undefined} rowNotes={page.kind==='history'?collections.history.map(e=>new Date(e.played_at).toLocaleString('ru')):undefined}/>;
  return <div className={`library-content phase-two${page.kind==='search'?' unified-search-page':''}${searchEmpty?' unified-search-empty':''}`}>
    <div className="library-heading"><div className={`library-art ${page.kind==='liked'?'heart-art':''}`}>{page.kind==='album'&&raw[0]?<Cover track={raw.find(t=>t.cover)||raw[0]}/>:icon}</div><div className="collection-heading-copy"><h1>{title}</h1><p>{grid?`${cards.length} ${page.kind==='artists'?'исполнителей':page.kind==='albums'?'альбомов':'плейлистов'}`:`${tracks.length} треков · ${time(tracks.reduce((s,t)=>s+t.duration,0))}`}{page.kind==='album'&&raw[0]&&` · ${raw[0].album_artist}`}{page.kind==='history'&&' · последние 200 запусков'}{page.kind==='queue'&&' · текущий сеанс'}</p>{playlist?.description&&<p className="playlist-description">{playlist.description}</p>}</div></div>
    <div className="library-toolbar">
      {page.kind==='search'&&<form className="search unified-search-form" onSubmit={e=>{e.preventDefault();soulseek.onSearch();}}><Search size={18}/><input autoFocus placeholder="Найти музыку" aria-label="Поиск музыки" value={query} onChange={e=>onQueryChange(e.target.value)}/>{query&&<button type="button" className="icon-button" aria-label="Очистить поиск" onClick={()=>onQueryChange('')}><X size={15}/></button>}<button className="primary-button" type="submit" disabled={!query.trim()||!soulseek.enabled||!soulseek.configured}><Search size={15}/>Искать</button></form>}
      {!grid&&<button className="round-play" aria-label="Слушать список" disabled={!tracks.length||player.busy} onClick={()=>page.kind==='queue'?void player.jump(player.queue.cursor+1):void player.play(tracks[0],tracks,0,playlist?{kind:'playlist',playlistId:playlist.id}:undefined)}><Play size={23} fill="currentColor"/></button>}
      {toolbarLabel&&<span className="toolbar-label">{toolbarLabel}</span>}
      {page.kind==='playlists'&&<button className="primary-button" onClick={()=>setEditor(true)}><Plus size={17}/>Новый плейлист</button>}
      {playlist&&<><button className="icon-button" aria-label="Изменить плейлист" onClick={()=>setEditor(playlist)}><Pencil size={18}/></button><button className="icon-button" aria-label="Удалить плейлист" onClick={()=>setDeleteOpen(playlist)}><Trash2 size={18}/></button></>}
      {page.kind==='queue'&&<button className="subtle-button" disabled={!tracks.length||player.busy} onClick={player.clearUpcoming}>Очистить следующие</button>}
      {page.kind==='library'&&<button className="icon-button" aria-label="Обновить библиотеку" disabled={scanning||!library.folders.length} onClick={onScan}><RefreshCw size={18}/></button>}
      {!fixedOrder&&<><select aria-label="Сортировка" value={sort} onChange={e=>setSort(e.target.value as Sort)}>{(grid?['default','title'] as Sort[]:Object.keys(sortLabels) as Sort[]).map(s=><option key={s} value={s}>{sortLabels[s]}</option>)}</select><button className="icon-button" aria-label={descending?'По возрастанию':'По убыванию'} onClick={()=>setDescending(!descending)}>{descending?<ArrowDown size={18}/>:<ArrowUp size={18}/>}</button></>}
    </div>
    {page.kind==='queue'&&player.current&&<div className="queue-current"><Cover track={player.current} size="small"/><div><small>СЕЙЧАС {player.status.playing?'ИГРАЕТ':'НА ПАУЗЕ'}</small><strong>{player.current.title}</strong><small>{player.current.artist}</small></div><button className="subtle-button" onClick={()=>void player.toggle()}>{player.status.playing?'Пауза':'Продолжить'}</button></div>}
    {page.kind==='search'?<div className="unified-search-content"><section className="unified-search-section unified-search-library"><div className="unified-search-heading"><h2>Медиатека</h2><small>Найдено: {tracks.length}</small></div><div className={`unified-search-library-list${tracks.length?'':' is-empty'}`}>{trackList}</div></section><section className="unified-search-section unified-search-soulseek"><div className="unified-search-heading"><h2>Soulseek</h2></div><SoulseekSearchView query={query} request={soulseek.request} enabled={soulseek.enabled} configured={soulseek.configured} onDownload={soulseek.onDownload} downloadState={soulseek.downloadState}/></section></div>:grid?<EntityGrid items={sortedCards} artists={page.kind==='artists'} onOpen={id=>navigate({kind:page.kind==='artists'?'artist':page.kind==='albums'?'album':'playlist',id})} onContextMenu={(target,point)=>setCollectionMenu({target,point})} dropTargets={page.kind==='playlists'}/>:<div className="collection-track-area" data-playlist-id={playlist?.id}>{trackList}</div>}
    {editor&&<PlaylistEditor playlist={editor===true?undefined:editor} onClose={()=>setEditor(null)} mutate={mutate} busy={busy} onSaved={id=>navigate({kind:'playlist',id})}/>}
    {deleteOpen&&<ActionDialog track={byId.get(deleteOpen.entries[0]?.track_id)||{title:deleteOpen.name,artist:'Удалить только плейлист? Музыкальные файлы останутся.',cover:null} as Track} onClose={()=>setDeleteOpen(null)}><p>Плейлист и его порядок будут удалены.</p><button className="subtle-button" disabled={busy} onClick={async()=>{if(await mutate({type:'delete_playlist',id:deleteOpen.id})){const wasOpen=page.kind==='playlist'&&page.id===deleteOpen.id;setDeleteOpen(null);if(wasOpen)navigate({kind:'playlists'});}}}>Удалить плейлист</button></ActionDialog>}
    {actions&&<ActionDialog track={actions.track} onClose={()=>setActions(null)}><div className="track-action-list"><button disabled={player.busy} onClick={()=>{player.enqueue(actions.track,true);notice('Трек будет играть следующим');setActions(null);}}><Play size={17}/>Слушать следующим</button><button disabled={player.busy} onClick={()=>{player.enqueue(actions.track);notice('Трек добавлен в очередь');setActions(null);}}><ListMusic size={17}/>Добавить в очередь</button>
      {collections.playlists.length?<form onSubmit={e=>{e.preventDefault();void mutateClose({type:'add_tracks',id:Number(destination),track_ids:[actions.track.id]});}}><label htmlFor="destination-playlist">Добавить в плейлист</label><div className="path-input"><select id="destination-playlist" value={destination} onChange={e=>setDestination(e.target.value)}>{collections.playlists.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="primary-button" disabled={busy||!destination}>Добавить</button></div></form>:<button onClick={()=>{setActions(null);setEditor(true);}}><Plus size={17}/>Создать первый плейлист</button>}
      {playlist&&<div className="entry-actions"><button disabled={busy||actions.index===0} onClick={()=>void mutateClose({type:'move_entry',id:playlist.id,entry_id:playlist.entries[actions.index].id,index:actions.index-1})}><ArrowUp size={16}/>Выше</button><button disabled={busy||actions.index===tracks.length-1} onClick={()=>void mutateClose({type:'move_entry',id:playlist.id,entry_id:playlist.entries[actions.index].id,index:actions.index+1})}><ArrowDown size={16}/>Ниже</button><button disabled={busy} onClick={()=>void mutateClose({type:'remove_entry',id:playlist.id,entry_id:playlist.entries[actions.index].id})}><Trash2 size={16}/>Убрать из плейлиста</button></div>}
      {page.kind==='queue'&&<div className="entry-actions"><button disabled={player.busy||actions.index===0} onClick={()=>{const i=player.queue.cursor+1+actions.index;player.move(player.queue.items[i].key,i-1);setActions(null);}}><ArrowUp size={16}/>Выше</button><button disabled={player.busy||actions.index===tracks.length-1} onClick={()=>{const i=player.queue.cursor+1+actions.index;player.move(player.queue.items[i].key,i+1);setActions(null);}}><ArrowDown size={16}/>Ниже</button><button disabled={player.busy} onClick={()=>{player.remove(player.queue.items[player.queue.cursor+1+actions.index].key);setActions(null);}}><Trash2 size={16}/>Убрать из очереди</button></div>}
    </div></ActionDialog>}
    {contextMenu&&<TrackContextMenu track={contextMenu.track} point={contextMenu.point} busy={busy||player.busy} liked={likes.has(contextMenu.track.id)} playlists={collections.playlists} trashAvailable={trashAvailable} onPlayNext={()=>player.enqueue(contextMenu.track,true)} onAddToQueue={()=>player.enqueue(contextMenu.track)} onAddToLiked={()=>mutate({type:'like',track_id:contextMenu.track.id,liked:true})} onAddToPlaylist={destination=>mutate(playlistAddAction(destination.id,[contextMenu.track]))} onMoveToTrash={onMoveToTrash} onRemoveFromLibrary={onRemoveFromLibrary} onViewMetadata={onViewMetadata} onNotice={notice} onClose={()=>setContextMenu(null)}/>}
    {collectionMenu&&<CollectionContextMenu target={collectionMenu.target} point={collectionMenu.point} busy={busy||player.busy} playlists={collections.playlists} onPlay={()=>player.play(collectionMenu.target.tracks[0],collectionMenu.target.tracks,0,collectionMenu.target.kind==='playlist'?{kind:'playlist',playlistId:collectionMenu.target.id}:undefined)} onPlayNext={()=>enqueueGroup(collectionMenu.target.tracks,true,player.enqueue)} onAddToQueue={()=>enqueueGroup(collectionMenu.target.tracks,false,player.enqueue)} onAddToPlaylist={destination=>mutate(playlistAddAction(destination.id,collectionMenu.target.tracks))} onRename={()=>{if(collectionMenu.target.kind==='playlist')setEditor(collectionMenu.target.playlist);}} onDelete={()=>{if(collectionMenu.target.kind==='playlist')setDeleteOpen(collectionMenu.target.playlist);}} onNotice={notice} onClose={()=>setCollectionMenu(null)}/>}
  </div>;
}
