import { invoke } from '@tauri-apps/api/core';
import { Download } from 'lucide-react';
import { useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react';
import { filterSoulseekResults, performSoulseekSearch, remoteFilename, resultFacts, sortSoulseekResults, type QualityFilter, type ResultSort, type SoulseekReply, type SoulseekResult, type SoulseekState } from './soulseekSearch';

type Request={id:number;query:string}|null;
const labels:Record<SoulseekState['kind'],string>={ready:'Готово',searching:'Поиск…',not_configured:'Soulseek недоступен',authentication_failed:'Ошибка авторизации',unreachable:'slskd недоступен',failed:'Ошибка поиска или превышено время ожидания'};
export default function SoulseekSearchView({query,request,enabled,configured,onDownload,downloadState}:{query:string;request:Request;enabled:boolean;configured:boolean;onDownload:(result:SoulseekResult)=>void;downloadState:(result:SoulseekResult)=>'pending'|'added'|null}){
  const [state,setState]=useState<SoulseekState>({kind:enabled&&configured?'ready':'not_configured',results:[]});
  const latest=useRef(0);
  const [quality,setQuality]=useState<QualityFilter>('all'),[minimumBitrate,setMinimumBitrate]=useState(0),[minimumSampleRate,setMinimumSampleRate]=useState(0),[minimumBitDepth,setMinimumBitDepth]=useState(0),[sort,setSort]=useState<ResultSort>('default');
  useLayoutEffect(()=>{if(request)latest.current=request.id;},[request]);
  useEffect(()=>{if(!request)return;latest.current=request.id;if(!enabled||!configured){setState({kind:'not_configured',results:[]});return;}setState({kind:'searching',results:[]});void performSoulseekSearch(request.query,()=>latest.current===request.id,q=>invoke<SoulseekReply>('slskd_search',{query:q})).then(next=>{if(next)setState(next);});},[request,enabled,configured]);
  useEffect(()=>{if(!enabled||!configured)setState({kind:'not_configured',results:[]});else if(state.kind==='not_configured')setState({kind:'ready',results:[]});},[enabled,configured]);
  const results=state.results;
  const visible=useMemo(()=>sortSoulseekResults(filterSoulseekResults(results,{quality,minimumBitrate,minimumSampleRate,minimumBitDepth}),sort),[results,quality,minimumBitrate,minimumSampleRate,minimumBitDepth,sort]);
  return <div className="soulseek-search">
    <div className="soulseek-action"><span role="status">{state.kind==='ready'&&results.length?`Показано ${visible.length} из ${results.length}`:state.kind==='ready'&&request?'Ничего не найдено':labels[state.kind]}</span></div>
    {state.kind==='ready'&&results.length>0&&<div className="soulseek-controls"><select aria-label="Качество" value={quality} onChange={e=>setQuality(e.target.value as QualityFilter)}><option value="all">Все форматы</option><option value="lossless">Без потерь</option><option value="flac">FLAC</option><option value="mp3_320">MP3 320 кбит/с</option></select><label>Мин. битрейт <input type="number" min="0" step="1" value={minimumBitrate||''} placeholder="Любой" onChange={e=>setMinimumBitrate(Number(e.target.value))}/><span>кбит/с</span></label><label>Частота <select value={minimumSampleRate} onChange={e=>setMinimumSampleRate(Number(e.target.value))}><option value="0">Любая</option><option value="44100">≥ 44,1 кГц</option><option value="48000">≥ 48 кГц</option><option value="88200">≥ 88,2 кГц</option><option value="96000">≥ 96 кГц</option><option value="192000">≥ 192 кГц</option></select></label><label>Разрядность <select value={minimumBitDepth} onChange={e=>setMinimumBitDepth(Number(e.target.value))}><option value="0">Любая</option><option value="16">≥ 16 бит</option><option value="24">≥ 24 бит</option><option value="32">≥ 32 бит</option></select></label><label>Сортировка <select value={sort} onChange={e=>setSort(e.target.value as ResultSort)}><option value="default">По релевантности</option><option value="size">По размеру</option><option value="bitrate">По битрейту</option><option value="sample_rate">По частоте</option><option value="availability">По доступности</option></select></label></div>}
    {state.kind==='not_configured'?<p className="soulseek-unavailable" role="status">Soulseek недоступен</p>:state.kind!=='ready'?<div className="soulseek-state"><p>{labels[state.kind]}</p></div>:!request?<div className="soulseek-state"><p>{query.trim()?'Нажмите «Искать» для поиска в Soulseek.':'Введите запрос для поиска в Soulseek.'}</p></div>:!results.length?<div className="soulseek-state"><p>Ничего не найдено. Попробуйте сократить запрос или проверить исполнителя и название.</p></div>:!visible.length?<div className="soulseek-state"><p>Нет результатов с такими фильтрами. Измените параметры качества.</p></div>:<div className="soulseek-results">{visible.map((result,index)=><Result key={`${result.search_id}-${result.username}-${result.remote_path}-${index}`} result={result} onDownload={onDownload} actionState={downloadState(result)}/>)}</div>}
  </div>;
}
function Result({result,onDownload,actionState}:{result:SoulseekResult;onDownload:(result:SoulseekResult)=>void;actionState:'pending'|'added'|null}){
  const facts=resultFacts(result);
  return <article className="soulseek-result"><div><strong>{remoteFilename(result.remote_path)}</strong><small>{result.username}</small><small className="remote-path">{result.remote_path}</small></div><div className="soulseek-facts">{facts.map(fact=><span key={fact}>{fact}</span>)}</div><button className="subtle-button soulseek-download" disabled={actionState!==null} onClick={()=>onDownload(result)}><Download size={15}/>{actionState==='pending'?'Запуск…':actionState==='added'?'Добавлено':'Скачать'}</button></article>;
}
