import assert from 'node:assert/strict';
import test from 'node:test';
import { localSearchSource } from './libraryModel.ts';
import { filterSoulseekResults, formatBytes, formatDuration, performSoulseekSearch, remoteFilename, resultFacts, sortSoulseekResults, type SoulseekFilters, type SoulseekReply, type SoulseekResult } from './soulseekSearch.ts';

const reply=(results:SoulseekResult[]=[],completion:SoulseekReply['completion']='complete'):SoulseekReply=>({search_id:'id',completion,results,cleanup_succeeded:true});
test('local search is case-insensitive substring matching on title, artist, and album',async()=>{const tracks=[{id:7,title:'Track',artist:'Artist',album_artist:'Different Artist',album:'Album',genre:'Hidden genre',duration:1},{id:8,title:'Other',artist:'Кириллица',album_artist:'',album:'Синий Альбом',genre:'',duration:1}] as never[];const source=localSearchSource(tracks);for(const [query,id] of [['rAc',7],['TIST',7],['bum',7],['киР',8],['альб',8]] as const){assert.deepEqual((await source.search(query,new AbortController().signal)).map(hit=>hit.localTrackId),[id],query);}assert.deepEqual(await source.search('genre',new AbortController().signal),[]);assert.deepEqual(await source.search('',new AbortController().signal),[]);});
test('one explicit request produces one remote call and results',async()=>{let calls=0;const state=await performSoulseekSearch('artist',()=>true,async()=>{calls++;return reply();});assert.equal(calls,1);assert.deepEqual(state,{kind:'ready',results:[]});});
test('stale remote response arriving after a newer query is ignored',async()=>{let latest=1,release:(value:SoulseekReply)=>void=()=>{};const pending=new Promise<SoulseekReply>(resolve=>{release=resolve;});const old=performSoulseekSearch('old',()=>latest===1,async()=>pending);latest=2;const current=await performSoulseekSearch('new',()=>latest===2,async()=>reply([result('new.flac','flac',null,96000,24)]));assert.equal(current?.results[0].remote_path,'new.flac');release(reply([result('old.flac','flac',null,96000,24)]));assert.equal(await old,null);});
test('remote error states are classified',async()=>{for(const [message,kind] of [['slskd: API key not configured','not_configured'],['slskd: authentication failed','authentication_failed'],['slskd: request failed','unreachable'],['slskd: search timeout','failed']] as const)assert.equal((await performSoulseekSearch('x',()=>true,async()=>{throw message;}))?.kind,kind);});
test('optional metadata is formatted and missing values stay hidden',()=>{const result={source:'soulseek',search_id:'id',username:'peer',remote_path:'folder\\track.flac',size_bytes:1536*1024,extension:'flac',bitrate_kbps:900,sample_rate_hz:44100,bit_depth:24,duration_seconds:3661,has_free_upload_slot:true,queue_length:0,upload_speed_bytes_per_second:2*1024**2,is_locked:false} satisfies SoulseekResult;assert.deepEqual(resultFacts(result),['FLAC','1,5 МБ','900 кбит/с','44,1 кГц','24 бит','1:01:01','Свободный слот','В очереди: 0','2 МБ/с','Открыт']);assert.deepEqual(resultFacts({...result,extension:null,bitrate_kbps:null,sample_rate_hz:null,bit_depth:null,duration_seconds:null,has_free_upload_slot:null,queue_length:null,upload_speed_bytes_per_second:null}),['1,5 МБ','Открыт']);assert.equal(formatBytes(2*1024**3),'2 ГБ');assert.equal(formatDuration(65),'1:05');assert.equal(remoteFilename(result.remote_path),'track.flac');assert.equal('localTrackId' in result,false);});
const result=(name:string,extension:string|null,bitrate:number|null,sampleRate:number|null,bitDepth:number|null,size=1,free:boolean|null=null,queue:number|null=null,speed:number|null=null):SoulseekResult=>({source:'soulseek',search_id:'id',username:'peer',remote_path:name,size_bytes:size,extension,bitrate_kbps:bitrate,sample_rate_hz:sampleRate,bit_depth:bitDepth,duration_seconds:null,has_free_upload_slot:free,queue_length:queue,upload_speed_bytes_per_second:speed,is_locked:false});
const all: SoulseekFilters={quality:'all',minimumBitrate:0,minimumSampleRate:0,minimumBitDepth:0};
test('lossless and FLAC filters use normalized format',()=>{const items=[result('a.flac','flac',null,96000,24),result('b.wav','wav',null,44100,16),result('c.mp3','mp3',320,44100,null),result('unknown',null,null,null,null)];assert.deepEqual(filterSoulseekResults(items,{...all,quality:'lossless'}).map(x=>x.remote_path),['a.flac','b.wav']);assert.deepEqual(filterSoulseekResults(items,{...all,quality:'flac'}).map(x=>x.remote_path),['a.flac']);});
test('MP3 320 and numeric filters require their metadata',()=>{const items=[result('320.mp3','mp3',320,48000,24),result('256.mp3','mp3',256,44100,16),result('missing.mp3','mp3',null,null,null),result('flac.flac','flac',1000,96000,24)];assert.deepEqual(filterSoulseekResults(items,{...all,quality:'mp3_320'}).map(x=>x.remote_path),['320.mp3']);assert.deepEqual(filterSoulseekResults(items,{...all,minimumBitrate:300,minimumSampleRate:48000,minimumBitDepth:24}).map(x=>x.remote_path),['320.mp3','flac.flac']);assert.equal(filterSoulseekResults(items,all).length,4);});
test('sorting is stable and leaves missing metadata last',()=>{const items=[result('missing',null,null,null,null,10,null,null,null),result('slow','mp3',128,44100,null,20,false,4,100),result('fast','flac',null,96000,24,30,true,0,1000)];assert.deepEqual(sortSoulseekResults(items,'default'),items);assert.deepEqual(sortSoulseekResults(items,'size').map(x=>x.remote_path),['fast','slow','missing']);assert.deepEqual(sortSoulseekResults(items,'bitrate').map(x=>x.remote_path),['slow','missing','fast']);assert.deepEqual(sortSoulseekResults(items,'sample_rate').map(x=>x.remote_path),['fast','slow','missing']);assert.deepEqual(sortSoulseekResults(items,'availability').map(x=>x.remote_path),['fast','slow','missing']);});
test('local filters do not start another remote search',async()=>{let calls=0;const remote=result('track.flac','flac',null,96000,24);const state=await performSoulseekSearch('track',()=>true,async()=>{calls++;return reply([remote]);});assert.equal(state?.kind,'ready');filterSoulseekResults(state!.results,{...all,quality:'flac'});sortSoulseekResults(state!.results,'sample_rate');assert.equal(calls,1);});
