import { useEffect, useState } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { Copy, FileImage, FolderOpen, Heart, Info, ListMusic, Play, Trash2 } from 'lucide-react';
import type { Playlist, Track, TrackFileStatus } from './types';
import { ContextMenu, MenuItem, MenuSection, PlaylistSubmenu } from './ContextMenu';
import type { MenuPoint } from './trackContextMenuModel';

type Props={track:Track;point:MenuPoint;busy?:boolean;liked?:boolean;playlists:Playlist[];trashAvailable:boolean;onPlayNext:()=>void;onAddToQueue:()=>void;onAddToLiked:()=>void|Promise<unknown>;onAddToPlaylist:(playlist:Playlist)=>void|Promise<unknown>;onMoveToTrash:(track:Track)=>void;onRemoveFromLibrary:(track:Track)=>void;onViewMetadata:(track:Track)=>void;onClose:()=>void;onNotice?:(message:string)=>void};

export default function TrackContextMenu({track,point,busy=false,liked=false,playlists,trashAvailable,onPlayNext,onAddToQueue,onAddToLiked,onAddToPlaylist,onMoveToTrash,onRemoveFromLibrary,onViewMetadata,onClose,onNotice}:Props){
  const [fileStatus,setFileStatus]=useState<TrackFileStatus|'checking'|'error'>('checking');
  useEffect(()=>{let active=true;setFileStatus('checking');void invoke<TrackFileStatus>('track_file_status',{trackId:track.id}).then(status=>{if(active)setFileStatus(status);}).catch(error=>{if(active){setFileStatus('error');onNotice?.(String(error));}});return()=>{active=false;};},[track.id,onNotice]);
  return <ContextMenu point={point} label={`Действия с треком ${track.title}`} onClose={onClose} onNotice={onNotice}>{run=>{
  const copy=(value:string,label:string)=>run(()=>invoke('copy_system_text',{text:value}),`${label} скопирован`);
  return <><MenuSection label="ВОСПРОИЗВЕДЕНИЕ"><MenuItem tooltip="Воспроизвести сразу после текущего трека" icon={<Play size={16}/>} disabled={busy} onClick={()=>void run(onPlayNext,'Трек будет играть следующим')}>Играть следующим</MenuItem><MenuItem tooltip="Добавить в конец очереди" icon={<ListMusic size={16}/>} disabled={busy} onClick={()=>void run(onAddToQueue,'Трек добавлен в очередь')}>Добавить в очередь</MenuItem><MenuItem icon={<Heart size={16} fill={liked?'currentColor':'none'}/>} disabled={busy||liked} onClick={()=>void run(onAddToLiked,'Трек добавлен в любимые')}>{liked?'Уже в любимых':'Добавить в любимые'}</MenuItem><PlaylistSubmenu playlists={playlists} disabled={busy} run={run} onSelect={onAddToPlaylist}/></MenuSection>
    <MenuSection label="КОПИРОВАТЬ"><MenuItem icon={<Copy size={16}/>} onClick={()=>void copy(track.title,'Название')}>Название</MenuItem><MenuItem icon={<Copy size={16}/>} onClick={()=>void copy(track.artist,'Исполнитель')}>Исполнитель</MenuItem><MenuItem icon={<Copy size={16}/>} onClick={()=>void copy(track.album,'Альбом')}>Альбом</MenuItem>{track.cover&&<MenuItem icon={<FileImage size={16}/>} onClick={()=>void run(()=>invoke('copy_cover_image',{path:track.cover}),'Обложка скопирована')}>Обложку</MenuItem>}<MenuItem icon={<Copy size={16}/>} onClick={()=>void copy(track.path,'Путь')}>Путь к файлу</MenuItem></MenuSection>
    <MenuSection label="ФАЙЛ"><MenuItem icon={<Info size={16}/>} onClick={()=>void run(()=>onViewMetadata(track))}>Метаданные</MenuItem><MenuItem tooltip="Открыть папку с файлом" icon={<FolderOpen size={16}/>} disabled={fileStatus!=='present'} onClick={()=>void run(()=>invoke('show_in_file_explorer',{path:track.path}))}>Показать в Проводнике</MenuItem></MenuSection><MenuSection separated>{fileStatus==='missing'?<MenuItem destructive icon={<Trash2 size={16}/>} disabled={busy} onClick={()=>void run(()=>onRemoveFromLibrary(track))}>Убрать из медиатеки</MenuItem>:fileStatus==='present'?<MenuItem destructive tooltip="Переместить файл в папку удалённых песен" icon={<Trash2 size={16}/>} disabled={busy||!trashAvailable} onClick={()=>void run(()=>onMoveToTrash(track))}>Переместить в удалённые</MenuItem>:<MenuItem icon={<Trash2 size={16}/>} disabled onClick={()=>{}}>{fileStatus==='checking'?'Проверяем файл…':'Состояние файла неизвестно'}</MenuItem>}</MenuSection></>;
  }}</ContextMenu>;
}
